### ISSUE TITLE
In "Past Events" section, links are not very distinct from body text

### ISSUE THREAD

**Issue by brittag** [openhatch/oh-campus-foss#5]
In the blue-background area of http://campus.openhatch.org/, there are various weights and sizes of white text, where bold text means link, but that boldness is a bit subtle. I think it's easy to miss which parts are links and which parts aren't.

It could be helpful for the links to be underlined there as well as bold, for example.

**Comment by sri-teja** [comment]
Do you want those bold texts having links to be underlined?

**Comment by shaunagm** [comment]
@sri-teja, yes!  That would be great.

**Comment by sri-teja** [comment]
Yeah. I will do that.

**Comment by sri-teja** [comment]
@shaunagm, I did that underline thing for every bold text. What I have to do to merge that with the official one?

----- Original Message -----

**Comment by shaunagm** [comment]
You'll need to create a pull request.  Look at the right-hand side of your repository page on github - there should be a link there, which goes to another link, etc.  See here: https://help.github.com/articles/using-pull-requests/

That being said, I took a quick look at the changes you made.  Rather than editing all of the links individually, it would be much better to change the css file that controls how they're displayed.  That's this file: https://github.com/openhatch/oh-campus-foss/blob/master/static/css/style.css  This page has an overview: http://www.w3schools.com/css/css_link.asp

**Comment by sri-teja** [comment]
Thankyou @shaunagm

**Comment by shaunagm** [comment]
Thanks for making the change, @sri-teja!  I merged your pull request.

Looking at the page now, I think it might make sense to remove the underline specifically for the button links, with the css class "btn".  I'm also not thrilled with how the icon links look like in the past-events section.  Tedious, but we could add a class to all of the links with format:

"<a href="$""><span class="glyphicon glyphicon-picture"></span>  Pictures</a>"

So that it doesn't underline them.  Alternatively we could move the icons outside of the links, so we don't get that leading whitespace underline.

**Comment by shaunagm** [comment]
Looks great now.  Thank you, @sri-teja!  I'll close this issue.
